gpu_id: 0

model:
  type: MattingNetwork
  kwargs:
    variant: mobilenetv3
    refiner: deep_guided_filter
  path: pretrained/rvm_mobilenetv3.pth

data:
  videomatte_dir_train: data/VideoMatte240K_JPEG_SD/train
  background_video_dir_train: data/Backgrounds/train
  size: 512
  seq_length: 40
  batch_size: 4
  num_workers: 4

quant:
  w_qconfig:
    quantizer: AdaRoundFakeQuantize
    observer: MinMaxObserver
    bit: 8
    symmetric: true
    ch_axis: 0
  a_qconfig:
    quantizer: LSQFakeQuantize
    observer: AvgMinMaxObserver
    bit: 8
    symmetric: true
    ch_axis: -1
  calibrate: 128
  recon:
    iters: 20000
    b_range: [20, 2]
    warm_up: 0.0
    p: 2.0
    batch_size: 32
    drop_prob: 0.5
    round_mode: learned_hard_sigmoid
    weight: 0.01
    keep_gpu: true
    scale_lr: 4.0e-5

process:
  seed: 1029
