gpu_id: 0

model:
  type: MattingNetwork
  kwargs:
    variant: mobilenetv3
    refiner: deep_guided_filter
  path: pretrained/rvm_mobilenetv3.pth

data:
  videomatte_dir_train: data/VideoMatte240K_JPEG_SD/train
  background_video_dir_train: data/Backgrounds/train
  size: 512
  seq_length: 40
  batch_size: 4
  num_workers: 4

quant:
  w_qconfig:
    quantizer: FixedFakeQuantize
    observer: MinMaxObserver
    bit: 4
    symmetric: true
    ch_axis: -1
  a_qconfig:
    quantizer: FixedFakeQuantize
    observer: AvgMinMaxObserver
    bit: 8
    symmetric: true
    ch_axis: -1
  calibrate: 128
  recon:
    scale: 1.0e-5
    opt_mode: mse
    iters: 20000
    b_range: [20, 2]
    warmup: 0.0
    p: 2.0
    batch_size: 32
    drop_prob: 0.5

process:
  seed: 1029
